### ISSUE TITLE
travis: fix build failure

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-formatter#64]
https://travis-ci.org/github/inveniosoftware/invenio-formatter/jobs/664497132#L311

```
$ requirements-builder --level=min setup.py > .travis-lowest-requirements.txt
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/bin/requirements-builder", line 8, in <module>
    sys.exit(cli())
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/requirements_builder/cli.py", line 69, in cli
    output.writelines(lines)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/click/_compat.py", line 88, in writelines
    for line in lines:
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/requirements_builder/cli.py", line 66, in <genexpr>
    '{0}\n'.format(req)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/requirements_builder/requirements_builder.py", line 108, in iter_requirements
    exec(setup_fp.read(), g)
  File "<string>", line 0
SyntaxError: encoding declaration in Unicode string
The command "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt" failed and exited with 1 during .
```

**Comment by lnielsen** [comment]
- Problem is similar to inveniosoftware/invenio-app#63

*Tasks*
- Remove python 2 support according to the [Python 2 support RFC](https://github.com/inveniosoftware/rfcs/blob/master/framework/0016-python2.md) in order to fix build error.
- Likely the same problem as in Invenio-App will happen where another build error will be triggered due to six version conflict.
